### ISSUE TITLE
Sample App Asks for Unnecessary Info on Register

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-sdk-angularjs#164]
The sample app registration page looks like this:

![screenshot 2016-08-05 10 33 43](https://cloud.githubusercontent.com/assets/90247/17445111/22ad87ae-5af8-11e6-80f9-b851657c4f81.png)

This is confusing because: why do I need to supply first name / last name / favorite color if that info is not used anywhere else in this demo? Seems unnecessary, and just adds confusion.

**Comment by robertjd** [comment]
Well, it _is_ shown on the "profile" page, but it's the lamest profile page ever because you can't actually edit anything :)

I actually want to remove this example application in favor of the [Stormpath Angular + Express Fullstack Sample Project](https://github.com/stormpath/express-stormpath-angular-sample-project).  See #166 for the full plain I'm setting out.

Closing issue, please follow up if that plan doesn't address the concern.
