### ISSUE TITLE
Cookie not being sent, when using a different backend port

### ISSUE THREAD

**Issue by n8twj** [stormpath/stormpath-sdk-angularjs#5]
Maybe this is my node/angular/js noobie showing, but I have altered the STORMPATH_CONFIG, since i run two separate apps ('frontend'  (angularjs) and 'backend' (node json api))

(Warning:  CoffeeScript) 

angular.module('app.controllers', [
    'stormpath'
])
.config( (STORMPATH_CONFIG) -> 
  STORMPATH_CONFIG.AUTHENTICATION_ENDPOINT = 'http://localhost:9000/oauth/token'
  STORMPATH_CONFIG.CURRENT_USER_URI = 'http://localhost:9000/api/users/current'
)
...

When I do this, the two set-cookie's from /oauth/token are not sent back to /api/users/current.  Not certain if there is something else I need to adjust on my node backend script or not.  Hoping someone might know what is going on.    I will post code, as requested.

**Comment by n8twj** [comment]
![screen shot 2015-02-14 at 10 55 12 pm](https://cloud.githubusercontent.com/assets/5016817/6202020/9a1f16b2-b49c-11e4-953b-4d5c9799d5bb.png)
![screen shot 2015-02-14 at 10 55 21 pm](https://cloud.githubusercontent.com/assets/5016817/6202021/9edc44ae-b49c-11e4-8bf7-15a9e1579978.png)

**Comment by robertjd** [comment]
Hi @n8twj !

Requests to a different port will be considered cross-domain, do you see errors about that in the console?

If you are using our Express SDK you can whitelist localhost:3333 with this option:

https://github.com/stormpath/stormpath-sdk-express#allowedOrigins

**Comment by n8twj** [comment]
I will try that specific option.... I have allowed for cors with header
options on server side.

**Comment by n8twj** [comment]
Previously worked thru the various errors about cross domain - everything
seems to be working, just no cookie being sent back

**Comment by robertjd** [comment]
Hey again.  The issue here is, unfortunately, still with CORS.  Because the cookie is being sent by the :9000 domain, only pages on that domain will send the cookie to the server.  That's why it seems like the cookie isn't being set, but really it just isn't readable from the :3333 domain.

The workaround is to manually store the access token in local storage.  The local storage area is vulnerable to XSS attacks, so you must have confidence that no malicious scripts will find their way onto your app.

I'm adding some code to this library which will do this automatically, I'll let you know when I have it (should be a day or two).  In the meantime you can experiment by enabling the access token response in the express SDK with the `writeAccessTokenResponse` option - this will make the access token available in the response body so that Angular can read it.  Note: I just updated that library with a fix, you'll need to update it.

**Comment by n8twj** [comment]
I will absolutely take a look at that option.   In the mean time, I combined my frontend and backend apps.   I am using Brunch.io (vs Grunt/Gulp)... What I am seeing now is two XSRF-TOKEN cookies getting set, but I cannot explain why... also access_token is not showing up as a detected cookie.   Any ideas would be appreciated.   Your example app does not experience this behavior  :( 

![screen shot 2015-02-16 at 2 08 11 pm](https://cloud.githubusercontent.com/assets/5016817/6217752/42215bce-b5e5-11e4-94bd-2872b83a0270.png)

![screen shot 2015-02-16 at 2 04 48 pm](https://cloud.githubusercontent.com/assets/5016817/6217743/1cde83e6-b5e5-11e4-90df-2fa9f6928805.png)

**Comment by n8twj** [comment]
As I suspected....Upon digging into Brunch.io, I discovered they use pushserver, which by default adds CORS protection.

Adding xsrf: false  to config for development usage is working for me

**Comment by robertjd** [comment]
CORS is now possible with this library, using the ENDPOINT_PREFIX option in STORMPATH_CONFIG.  You need to ensure that your back-end server is setting the appropriate headers (allowing requests from the other domain, and allowing credentialed requests from the other domain).
